__all__ = ["reverse_funcnode", "subagent_spawn", "jump_funcnode"]

from core.states import OrchestratorState


def reverse_funcnode(state: OrchestratorState): ...
def subagent_spawn(state: OrchestratorState): ...
def jump_funcnode(state: OrchestratorState): ...
